# Generated by Django 5.2.1 on 2025-05-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('bilhete', models.CharField(max_length=14, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('data_contratacao', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
