# Generated by Django 5.2.1 on 2025-05-14 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRH', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='salario',
            new_name='salario_base',
        ),
        migrations.CreateModel(
            name='Folha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('mes_ano', models.DateField()),
                ('salario_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descontos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folha_salario', to='SGRH.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
