# Generated by Django 5.2.1 on 2025-05-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRH', '0003_departamento_funcionario_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGRH.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
