# Generated by Django 5.2.1 on 2025-05-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRH', '0004_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
