# Generated by Django 5.2.1 on 2025-05-14 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRH', '0007_alter_ponto_funcionario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folha',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGRH.funcionario'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_departamento', to='SGRH.departamento'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGRH.funcionario'),
        ),
        migrations.CreateModel(
            name='Feria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Aprovada'), ('R', 'Rejeitada')], max_length=1)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGRH.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
