# Generated by Django 5.2.1 on 2025-05-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRH', '0008_alter_folha_funcionario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo', models.CharField(choices=[('T', 'Transporte'), ('R', 'Refeição')], max_length=1)),
                ('descricacao', models.CharField(max_length=225)),
                ('status', models.CharField(choices=[('B', 'Beneficiado'), ('N', 'Não beneficiado')], max_length=1)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGRH.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
