# Generated by Django 5.2.1 on 2025-05-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRH', '0009_beneficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('data', models.DateField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGRH.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
