# Generated by Django 5.2.1 on 2025-05-15 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRH', '0010_treinamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('ND', 'Não disponível')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidato', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('EA', 'Em análise'), ('C', 'Contratado'), ('R', 'Rejeito')], max_length=2)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGRH.areas')),
            ],
        ),
    ]
