from .geral import Geral
from .departamento import Departamento
from .funcionario import Funcionario
from .folhaDeSalario import Folha
from .contacto import Contacto
from .livroDePontos import Ponto
from .cargo import Cargo
from .ferias import Feria
from .beneficios import Beneficio
from .treinamento import Treinamento
from .areas import Areas
from .candidaturas import Candidatura